name: Android Build

on:
  push:
    branches:
      - main # Puedes cambiar la rama en la que se desencadenará el flujo de trabajo
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.0' # Puedes cambiar a la versión de Flutter que necesites

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release # Puedes ajustar el comando según tus necesidades

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk # Asegúrate de especificar la ruta correcta al APK generado